AWSTemplateFormatVersion: 2010-09-09
Description: VPC

Parameters:
  EnvName:
    Type: String
    Default: prod

Resources:
  #WebCloudFrontCachePolicy:
  #  Type: AWS::CloudFront::CachePolicy
  #  Properties:
  #    CachePolicyConfig: 
  #      DefaultTTL: 0
  #      MaxTTL: 0
  #      MinTTL: 0
  #      Name: !Sub ${prod}-CachePolicy
  #      ParametersInCacheKeyAndForwardedToOrigin: 
  #        EnableAcceptEncodingBrotli: Boolean
  #        EnableAcceptEncodingGzip: Boolean
  #        CookiesConfig: 
  #          CookieBehavior: none
  #        HeadersConfig: 
  #          HeadersConfig
  #        QueryStringsConfig: 
  #          QueryStringsConfig

  WEBCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig: 
        Aliases: 
          - "ihihihihih123456.com"
          - "www.ihihihihih123456.com"
        Enabled: true
        IPV6Enabled: true
        Origins: 
          - CustomOriginConfig: 
              OriginProtocolPolicy: https-only
              OriginReadTimeout: 60
              OriginSSLProtocols:
                - TLSv1.2
            DomainName:
              Fn::ImportValue: ALBDNSNameExport
            Id: ALBOrigin
            #OriginAccessControlId: String
            OriginShield: 
              Enabled: true
              OriginShieldRegion: ap-northeast-1
            #S3OriginConfig: 
            #  S3OriginConfig
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          Compress: false
          #OriginRequestPolicyId: String
          #ResponseHeadersPolicyId: String
          TargetOriginId: ALBOrigin
          #TrustedKeyGroups: 
          #  - String
          ViewerProtocolPolicy: https-only
        #CacheBehaviors: 
        # - CacheBehavior
        HttpVersion: http2and3
        PriceClass: PriceClass_200
        ViewerCertificate: 
          AcmCertificateArn: arn:aws:acm:us-east-1:325812952166:certificate/227fa772-0158-4a20-ab90-13b042e20616
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        #WebACLId: String
      Tags: 
        - Key: Name
          Value: !Sub ${EnvName}-Distribution
