AWSTemplateFormatVersion: 2010-09-09
Description: VPC

Parameters:
  EnvName:
    Type: String
    Default: prod

Resources:
  WEBOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        CookiesConfig: 
          CookieBehavior: none
        HeadersConfig: 
          HeaderBehavior: whitelist
          Headers:
            - Origin
            - Host
            - Referer
        Name: !Sub ${EnvName}-WEB-OriginRequestPolicy
        QueryStringsConfig: 
          QueryStringBehavior: none

  WEBCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig: 
        Aliases: 
          - "ihihihihih123456.com"
          - "www.ihihihihih123456.com"
        Enabled: true
        IPV6Enabled: true
        Origins: 
          - CustomOriginConfig: 
              OriginProtocolPolicy: https-only
              OriginReadTimeout: 60
              OriginSSLProtocols:
                - TLSv1.2
            DomainName:
              Fn::ImportValue: ALBDNSNameExport
            Id: ALBOrigin
            #OriginAccessControlId: String
            OriginShield: 
              Enabled: true
              OriginShieldRegion: ap-northeast-1
            #S3OriginConfig:
            #  S3OriginConfig
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          Compress: false
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          #ResponseHeadersPolicyId: String
          TargetOriginId: ALBOrigin
          #TrustedKeyGroups: 
          #  - String
          ViewerProtocolPolicy: https-only
        CacheBehaviors: 
          - AllowedMethods:
              - GET
              - HEAD
            CachedMethods: 
              - GET
              - HEAD
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            Compress: true
            OriginRequestPolicyId: !Ref WEBOriginRequestPolicy
            PathPattern: /cache/*
            TargetOriginId: ALBOrigin
            ViewerProtocolPolicy: https-only
        HttpVersion: http2and3
        PriceClass: PriceClass_200
        ViewerCertificate: 
          AcmCertificateArn: arn:aws:acm:us-east-1:325812952166:certificate/227fa772-0158-4a20-ab90-13b042e20616
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        #WebACLId: String
      Tags: 
        - Key: Name
          Value: !Sub ${EnvName}-Distribution

Outputs:
  CloudFrontDNSName:
    Value: !GetAtt WEBCloudFront.DomainName
    Export:
      Name: CloudFrontDNSNameExport
