AWSTemplateFormatVersion: 2010-09-09
Description: EC2

Parameters:
  EnvName:
    Type: String
    Default: prod

Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyFormat: pem
      KeyName: !Sub ${EnvName}-KeyPair
      KeyType: ed25519
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-EC2

  Ec2SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId:
        Fn::ImportValue: 
          !Sub "${EnvName}-VPC-Output"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 27.131.238.0/24
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-SecurityGroup

  EC2:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: false
      EbsOptimized: false
      #IamInstanceProfile: String
      ImageId: ami-08ce76bae392de7dc
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: t3.nano
      KeyName: !Ref KeyPair
      Monitoring: false
      SecurityGroupIds: 
        - !Ref Ec2SSHSecurityGroup
      SourceDestCheck: true
      SubnetId:
        Fn::ImportValue: 
          !Sub "${EnvName}-PublicSubnet1a-Output"
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-EC2
      Tenancy: default
