AWSTemplateFormatVersion: 2010-09-09
Description: EC2

Parameters:
  EnvName:
    Type: String
    Default: prod

Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: false
      EbsOptimized: false
      #IamInstanceProfile: String
      ImageId: ami-08ce76bae392de7dc
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: t3.nano
      #KeyName: String
      Monitoring: false
      #SecurityGroupIds: 
      #  - String
      #SecurityGroups: 
      #  - String
      SourceDestCheck: true
      SubnetId:
        Fn::ImportValue: 
          !Sub "${EnvName}-PublicSubnet1a-Output"
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-EC2
      Tenancy: default
