AWSTemplateFormatVersion: 2010-09-09
Description: ROUTE53

Parameters:
  EnvName:
    Type: String
    Default: prod

Resources:
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "ihihihihih123456.com"

Outputs:
  HosteZoneID:
    Value: !Ref HostedZone
    Export:
      Name: !Sub ${EnvName}-HostedZone

