AWSTemplateFormatVersion: 2010-09-09
Description: ROUTE53 Recordset

Parameters:
  EnvName:
    Type: String
    Default: prod

Resources:
  RecordSet1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: !Sub ${EnvName}-HostedZone
      Name: ihihihihih123456.com
      Type: A
      AliasTarget: 
        DNSName:
          Fn::ImportValue: CloudFrontDNSNameExport
        HostedZoneId: Z2FDTNDATAQYW2
        #  Fn::ImportValue: CloudFrontHostedZoneIdExport

  RecordSet2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: !Sub ${EnvName}-HostedZone
      Name: www.ihihihihih123456.com
      Type: A
      AliasTarget: 
        DNSName:
          Fn::ImportValue: CloudFrontDNSNameExport
        HostedZoneId: Z2FDTNDATAQYW2
        #  Fn::ImportValue: CloudFrontHostedZoneIdExport
